import type { NextPage } from 'next'
import { Main } from '../components/Main'
import Head from 'next/head'
import { Header } from '../components/Header'
import { GlobalStyle } from '../styles/global'
import { useState } from 'react'
import { NewTrackerModal } from '../components/NewTrackerModal'
import Modal from 'react-modal'

Modal.setAppElement('#__next')

const Home: NextPage = () => {
  const [isNewTrackerModalOpen, setIsNewTrackerModalOpen] = useState(false)

  const handleNewTrackerModalOpen = () => {
    setIsNewTrackerModalOpen(true)
    console.log('modal is open')
  }

  const handleNewTrackerModalClose = () => {
    setIsNewTrackerModalOpen(false)
  }

  return (
    <>
      <GlobalStyle />
      <Head>
        <title>Week Track</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/hourglass.svg' />
      </Head>
      <Header onOpenNewTrackerModal={handleNewTrackerModalOpen} />
      <NewTrackerModal
        isOpen={isNewTrackerModalOpen}
        onClose={handleNewTrackerModalClose}
      />
      <Main />
    </>
  )
}

export default Home
