import type { NextPage } from 'next'
import Head from 'next/head'
import { Header } from '../components/Header'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Week Track</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/hourglass.svg' />
      </Head>
      <Header />
    </>
  )
}

export default Home
